# -*- coding: utf-8 -*-
"""trabalho02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U6Vjs6eaa-DyLegiGgIang-Agm2nHoQJ
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

# Ler os arquivos CSV
df1 = pd.read_csv('produto1.csv')
df2 = pd.read_csv('produto2.csv')
df3 = pd.read_csv('produto3.csv')

# Concatenar os DataFrames verticalmente (um abaixo do outro)
df_concatenado = pd.concat([df1, df2, df3])

# Salvar o DataFrame concatenado em um novo arquivo CSV, se desejar
df_concatenado.to_csv('arquivo_concatenado.csv', index=False)

from google.colab import files
files.download('arquivo_concatenado.csv')

import pandas as pd

df = pd.read_csv('produto1.csv')

df = pd.read_csv('produto2.csv')

df = pd.read_csv('produto3.csv')

df

df1

df2

print(df.columns)

print(df1.columns)

print(df2.columns)

list(df.columns)

list(df1.columns)

list(df2.columns)

df['PREÇO ATUAL'] = df['PREÇO ATUAL'].str.replace('.', '', regex=False)
df['PREÇO ATUAL'] = df['PREÇO ATUAL'].str.replace(',', '.', regex=False)
df['PREÇO ATUAL'] = df['PREÇO ATUAL'].str.replace('R$ ', '', regex=False)
df['PREÇO ATUAL'] = df['PREÇO ATUAL'].astype(float)

media_geral = df['PREÇO ATUAL'].mean()
desvio_padrao_geral = df['PREÇO ATUAL'].std()

print("Media geral: %.2f" % media_geral)
print("Desvio padrao geral: %.2f" % desvio_padrao_geral)

grouped = df.groupby('MARCA')['PREÇO ATUAL']

grouped.agg(['mean', 'std'])

result = grouped.agg(['mean', 'std'])
result.columns = ['Média', 'Desvio Padrão']

result.plot.bar()